name: Bug Report
description: Create a bug report to help us fix an issue
labels: [ "bug", "to-triage" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Please follow the instructions below.
        We will close issues that don't provide enough information.

        Provide a brief summary of the issue in the title above
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Please provide a brief summary of the issue and provide a summarised description in the title above.
    validations:
      required: true
  - type: textarea
    id: plugin-configuration
    attributes:
      label: Tell us about your plugin configuration
      description: |
          Include the **full** configuration of the plugin.
          ```groovy
             gitCommitId {
                 // ...
             }
          ```
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: What version of the Plugin are you using?
    validations:
      required: true
  - type: input
    id: gradle-version
    attributes:
      label: Gradle version
      description: What version of Gradle are you running? Simply include the output of ``./gradlew --version``.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        - [ ] Please provide all the steps to experience the issue (required)
        - [ ] Include any stack-traces or any error messages (required)
        - [ ] If you can provide a (public) project where this issue can be reproduced (optional)
          - You can use [the template](https://github.com/gradle/gradle-issue-reproducer) with a Gradle GitHub action set up to showcase your problem.
          - You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your Environment (optional)
      description: |
        Include as many relevant details about the environment you experienced the bug in.
        Are you running inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: |
        Feel free to add any other context or screenshots about the bug.
        How are you affected? What is your goal? Anything else?
    validations:
      required: false
