name: Bug Report
description: Create a bug report to help us fix an issue
labels: [ "bug", "to-triage" ]
assignees: [ ]
body:
    - type: markdown
      attributes:
          value: |
              Please follow the instructions below.
              We will close issues that don't provide enough information.
    - type: textarea
      id: describe-the-bug
      attributes:
          label: Describe the bug (required)
          description: Please provide a brief summary of the issue and provide a summarised description in the title above.
      validations:
          required: true
    - type: textarea
      id: plugin-configuration
      attributes:
          label: Tell us about your plugin configuration (required)
          description: Include the **full** configuration of the plugin.
          value: |
              ```groovy
              gitCommitId {
                  // ...
              }
              ```
      validations:
          required: true
    - type: input
      id: plugin-version
      attributes:
          label: Tell us about the Plugin version used (required)
          description: What version of the Plugin are you using?
      validations:
          required: true
    - type: textarea
      id: gradle-version
      attributes:
          label: Tell us about the Gradle version used (required)
          description: What version of Gradle are you running?.
          value: |
              ```bash
              ./gradlew --version
              // ????
              ```
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to Reproduce (required)
          description: |
              Please provide all the steps to experience the issue.
              E.g. I run the plugin with ``./gradlew clean build``...
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce-stack-traces
      attributes:
          label: Are there any stacktraces or any error messages? (required)
          description: |
              Include any stack-traces or any error messages that are included in ``./gradlew .... --stacktrace``.
              For your own troubleshooting you may want to enable the `verbose` mode of the plugin in your `build.gradle`:
              ```groovy
              gitCommitId {
                  verbose.set(true)
              }
              ```
          value: |
              **WARNING** You may **NOT** want to paste all the output that is produced with `verbose` publicly,
              since it **MAY** contain information you deem sensitive.
              Review this **CAREFULLY** before posting your issue!
              
              ```bash
              ./gradlew --stacktrace
              // ????
              ```
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce-public-project
      attributes:
          label: Is there a (public) project where this issue can be reproduced? (optional)
          description: |
              - You can use [the template](https://github.com/gradle/gradle-issue-reproducer) with a Gradle GitHub action set up to showcase your problem.
              - You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.
      validations:
          required: false
    - type: textarea
      id: environment
      attributes:
          label: Your Environment (optional)
          description: |
              Include as many relevant details about the environment you experienced the bug in.
              Are you running inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...?
      validations:
          required: false
    - type: textarea
      id: context
      attributes:
          label: Context (optional)
          description: |
              Feel free to add any other context or screenshots about the bug.
              How are you affected? What is your goal? Anything else?
      validations:
          required: false
